######################################################################
# Automatically generated by qmake (2.01a) ? 10? 8 20:04:00 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . src
INCLUDEPATH += . src

# Input
HEADERS += src/data.h src/MainWindow.h
SOURCES += src/data.cpp src/main.cpp src/MainWindow.cpp
