#############################################################################
# Makefile for building: bingo
# Generated by qmake (2.01a) (Qt 4.7.2) on: ? 1? 3 11:20:45 2013
# Project:  bingo.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile bingo.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -m32 -march=i686 -mtune=generic -fasynchronous-unwind-tables -fno-strict-aliasing -fno-schedule-insns2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -m32 -march=i686 -mtune=generic -fasynchronous-unwind-tables -fno-strict-aliasing -fno-schedule-insns2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/lib/qt-4.7.2/mkspecs/linux-g++ -I. -I/usr/lib/qt-4.7.2/include/QtCore -I/usr/lib/qt-4.7.2/include/QtGui -I/usr/lib/qt-4.7.2/include -I. -Isrc -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/qt-4.7.2/lib -lQtGui -L/usr/lib/qt-4.7.2/lib -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/data.cpp \
		src/main.cpp \
		src/MainWindow.cpp moc_MainWindow.cpp
OBJECTS       = data.o \
		main.o \
		MainWindow.o \
		moc_MainWindow.o
DIST          = /usr/lib/qt-4.7.2/mkspecs/common/g++-multilib.conf \
		/usr/lib/qt-4.7.2/mkspecs/common/unix.conf \
		/usr/lib/qt-4.7.2/mkspecs/common/linux.conf \
		/usr/lib/qt-4.7.2/mkspecs/qconfig.pri \
		/usr/lib/qt-4.7.2/mkspecs/modules/qt_webkit_version.pri \
		/usr/lib/qt-4.7.2/mkspecs/features/qt_functions.prf \
		/usr/lib/qt-4.7.2/mkspecs/features/qt_config.prf \
		/usr/lib/qt-4.7.2/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt-4.7.2/mkspecs/features/default_pre.prf \
		/usr/lib/qt-4.7.2/mkspecs/features/release.prf \
		/usr/lib/qt-4.7.2/mkspecs/features/default_post.prf \
		/usr/lib/qt-4.7.2/mkspecs/features/warn_on.prf \
		/usr/lib/qt-4.7.2/mkspecs/features/qt.prf \
		/usr/lib/qt-4.7.2/mkspecs/features/unix/thread.prf \
		/usr/lib/qt-4.7.2/mkspecs/features/moc.prf \
		/usr/lib/qt-4.7.2/mkspecs/features/resources.prf \
		/usr/lib/qt-4.7.2/mkspecs/features/uic.prf \
		/usr/lib/qt-4.7.2/mkspecs/features/yacc.prf \
		/usr/lib/qt-4.7.2/mkspecs/features/lex.prf \
		/usr/lib/qt-4.7.2/mkspecs/features/include_source_dir.prf \
		bingo.pro
QMAKE_TARGET  = bingo
DESTDIR       = 
TARGET        = bingo

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: bingo.pro  /usr/lib/qt-4.7.2/mkspecs/linux-g++/qmake.conf /usr/lib/qt-4.7.2/mkspecs/common/g++-multilib.conf \
		/usr/lib/qt-4.7.2/mkspecs/common/unix.conf \
		/usr/lib/qt-4.7.2/mkspecs/common/linux.conf \
		/usr/lib/qt-4.7.2/mkspecs/qconfig.pri \
		/usr/lib/qt-4.7.2/mkspecs/modules/qt_webkit_version.pri \
		/usr/lib/qt-4.7.2/mkspecs/features/qt_functions.prf \
		/usr/lib/qt-4.7.2/mkspecs/features/qt_config.prf \
		/usr/lib/qt-4.7.2/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt-4.7.2/mkspecs/features/default_pre.prf \
		/usr/lib/qt-4.7.2/mkspecs/features/release.prf \
		/usr/lib/qt-4.7.2/mkspecs/features/default_post.prf \
		/usr/lib/qt-4.7.2/mkspecs/features/warn_on.prf \
		/usr/lib/qt-4.7.2/mkspecs/features/qt.prf \
		/usr/lib/qt-4.7.2/mkspecs/features/unix/thread.prf \
		/usr/lib/qt-4.7.2/mkspecs/features/moc.prf \
		/usr/lib/qt-4.7.2/mkspecs/features/resources.prf \
		/usr/lib/qt-4.7.2/mkspecs/features/uic.prf \
		/usr/lib/qt-4.7.2/mkspecs/features/yacc.prf \
		/usr/lib/qt-4.7.2/mkspecs/features/lex.prf \
		/usr/lib/qt-4.7.2/mkspecs/features/include_source_dir.prf \
		/usr/lib/qt-4.7.2/lib/libQtGui.prl \
		/usr/lib/qt-4.7.2/lib/libQtCore.prl
	$(QMAKE) -o Makefile bingo.pro
/usr/lib/qt-4.7.2/mkspecs/common/g++-multilib.conf:
/usr/lib/qt-4.7.2/mkspecs/common/unix.conf:
/usr/lib/qt-4.7.2/mkspecs/common/linux.conf:
/usr/lib/qt-4.7.2/mkspecs/qconfig.pri:
/usr/lib/qt-4.7.2/mkspecs/modules/qt_webkit_version.pri:
/usr/lib/qt-4.7.2/mkspecs/features/qt_functions.prf:
/usr/lib/qt-4.7.2/mkspecs/features/qt_config.prf:
/usr/lib/qt-4.7.2/mkspecs/features/exclusive_builds.prf:
/usr/lib/qt-4.7.2/mkspecs/features/default_pre.prf:
/usr/lib/qt-4.7.2/mkspecs/features/release.prf:
/usr/lib/qt-4.7.2/mkspecs/features/default_post.prf:
/usr/lib/qt-4.7.2/mkspecs/features/warn_on.prf:
/usr/lib/qt-4.7.2/mkspecs/features/qt.prf:
/usr/lib/qt-4.7.2/mkspecs/features/unix/thread.prf:
/usr/lib/qt-4.7.2/mkspecs/features/moc.prf:
/usr/lib/qt-4.7.2/mkspecs/features/resources.prf:
/usr/lib/qt-4.7.2/mkspecs/features/uic.prf:
/usr/lib/qt-4.7.2/mkspecs/features/yacc.prf:
/usr/lib/qt-4.7.2/mkspecs/features/lex.prf:
/usr/lib/qt-4.7.2/mkspecs/features/include_source_dir.prf:
/usr/lib/qt-4.7.2/lib/libQtGui.prl:
/usr/lib/qt-4.7.2/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile bingo.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/bingo1.0.0 || $(MKDIR) .tmp/bingo1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/bingo1.0.0/ && $(COPY_FILE) --parents src/data.h src/MainWindow.h .tmp/bingo1.0.0/ && $(COPY_FILE) --parents src/data.cpp src/main.cpp src/MainWindow.cpp .tmp/bingo1.0.0/ && (cd `dirname .tmp/bingo1.0.0` && $(TAR) bingo1.0.0.tar bingo1.0.0 && $(COMPRESS) bingo1.0.0.tar) && $(MOVE) `dirname .tmp/bingo1.0.0`/bingo1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/bingo1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_MainWindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_MainWindow.cpp
moc_MainWindow.cpp: src/data.h \
		src/MainWindow.h
	/usr/lib/qt-4.7.2/bin/moc $(DEFINES) $(INCPATH) src/MainWindow.h -o moc_MainWindow.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

data.o: src/data.cpp src/data.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o data.o src/data.cpp

main.o: src/main.cpp src/MainWindow.h \
		src/data.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

MainWindow.o: src/MainWindow.cpp src/MainWindow.h \
		src/data.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MainWindow.o src/MainWindow.cpp

moc_MainWindow.o: moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MainWindow.o moc_MainWindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

